### ISSUE TITLE
Gradle build of examples fails

### ISSUE THREAD

**Issue by masud-technope** [awslabs/djl#30]
## Description
**DJL** main project compiles with Gradle using the test option disabled (*-x test*). Unfortunately, I cannot build the **examples** folder with Gradle tool. It is showing some annoying compile errors. Based on my investigation, some class files from DJL are not visible from the example repository.

### Expected Behavior
Example repository should compile.

### Error Message
```
Microsoft Windows [Version 10.0.18362.657]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\MyWorks\DJL-AI\djl\examples>gradlew jar
Found C:\MyWorks\DJL-AI\djl\examples\\gradle\wrapper\gradle-wrapper.jar

> Task :compileJava FAILED
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\inference\ActionRecognition.java:20: error: cannot find symbol
import ai.djl.repository.zoo.Criteria;
                            ^
  symbol:   class Criteria
  location: package ai.djl.repository.zoo
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\inference\benchmark\util\AbstractBenchmark.java:21: error: cannot find symbol
import ai.djl.repository.zoo.Criteria;
                            ^
  symbol:   class Criteria
  location: package ai.djl.repository.zoo
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\inference\BertQaInference.java:20: error: cannot find symbol
import ai.djl.repository.zoo.Criteria;
                            ^
  symbol:   class Criteria
  location: package ai.djl.repository.zoo
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\inference\InstanceSegmentation.java:21: error: cannot find symbol
import ai.djl.repository.zoo.Criteria;
                            ^
  symbol:   class Criteria
  location: package ai.djl.repository.zoo
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\inference\ObjectDetection.java:21: error: cannot find symbol
import ai.djl.repository.zoo.Criteria;
                            ^
  symbol:   class Criteria
  location: package ai.djl.repository.zoo
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\inference\PoseEstimation.java:24: error: cannot find symbol
import ai.djl.repository.zoo.Criteria;
                            ^
  symbol:   class Criteria
  location: package ai.djl.repository.zoo
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\training\TrainWithOptimizers.java:38: error: cannot find symbol
import ai.djl.repository.zoo.Criteria;
                            ^
  symbol:   class Criteria
  location: package ai.djl.repository.zoo
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\training\transferlearning\TrainResnetWithCifar10.java:38: error: cannot find symbol
import ai.djl.repository.zoo.Criteria;
                            ^
  symbol:   class Criteria
  location: package ai.djl.repository.zoo
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\inference\ActionRecognition.java:54: error: cannot find symbol
        Criteria<BufferedImage, Classifications> criteria =
        ^
  symbol:   class Criteria
  location: class ActionRecognition
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\inference\ActionRecognition.java:55: error: cannot find symbol
                Criteria.builder()
                ^
  symbol:   variable Criteria
  location: class ActionRecognition
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\inference\benchmark\util\AbstractBenchmark.java:191: error: package Criteria does not exist
        Criteria.Builder<I, O> builder =
                ^
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\inference\benchmark\util\AbstractBenchmark.java:192: error: cannot find symbol
                Criteria.builder()
                ^
  symbol:   variable Criteria
  location: class AbstractBenchmark<I,O>
  where I,O are type-variables:
    I extends Object declared in class AbstractBenchmark
    O extends Object declared in class AbstractBenchmark
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\inference\BertQaInference.java:64: error: cannot find symbol
        Criteria<QAInput, String> criteria =
        ^
  symbol:   class Criteria
  location: class BertQaInference
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\inference\BertQaInference.java:65: error: cannot find symbol
                Criteria.builder()
                ^
  symbol:   variable Criteria
  location: class BertQaInference
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\inference\InstanceSegmentation.java:58: error: cannot find symbol
        Criteria<BufferedImage, DetectedObjects> criteria =
        ^
  symbol:   class Criteria
  location: class InstanceSegmentation
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\inference\InstanceSegmentation.java:59: error: cannot find symbol
                Criteria.builder()
                ^
  symbol:   variable Criteria
  location: class InstanceSegmentation
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\inference\ObjectDetection.java:58: error: cannot find symbol
        Criteria<BufferedImage, DetectedObjects> criteria =
        ^
  symbol:   class Criteria
  location: class ObjectDetection
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\inference\ObjectDetection.java:59: error: cannot find symbol
                Criteria.builder()
                ^
  symbol:   variable Criteria
  location: class ObjectDetection
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\inference\PoseEstimation.java:76: error: cannot find symbol
        Criteria<BufferedImage, DetectedObjects> criteria =
        ^
  symbol:   class Criteria
  location: class PoseEstimation
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\inference\PoseEstimation.java:77: error: cannot find symbol
                Criteria.builder()
                ^
  symbol:   variable Criteria
  location: class PoseEstimation
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\inference\PoseEstimation.java:114: error: cannot find symbol
        Criteria<BufferedImage, Joints> criteria =
        ^
  symbol:   class Criteria
  location: class PoseEstimation
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\inference\PoseEstimation.java:115: error: cannot find symbol
                Criteria.builder()
                ^
  symbol:   variable Criteria
  location: class PoseEstimation
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\training\TrainWithOptimizers.java:128: error: package Criteria does not exist
        Criteria.Builder<BufferedImage, Classifications> builder =
                ^
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\training\TrainWithOptimizers.java:129: error: cannot find symbol
                Criteria.builder()
                ^
  symbol:   variable Criteria
  location: class TrainWithOptimizers
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\training\transferlearning\TrainResnetWithCifar10.java:123: error: package Criteria does not exist
        Criteria.Builder<BufferedImage, Classifications> builder =
                ^
C:\MyWorks\DJL-AI\djl\examples\src\main\java\ai\djl\examples\training\transferlearning\TrainResnetWithCifar10.java:124: error: cannot find symbol
                Criteria.builder()
                ^
  symbol:   variable Criteria
  location: class TrainResnetWithCifar10
26 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed

C:\MyWorks\DJL-AI\djl\examples> 
```

## How to Reproduce?
Used the official version from GitHub.

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Clone the ```https://github.com/awslabs/djl```
2. Build with ```gradlew build -x test```
3. Enter into examples using ```cd examples```
4. Try to build with ```gradlew jar```

## What have you tried to solve it?

1. Tried with all the provided comments, didn't work.
2. Tried with maven, didn't work.

## Environment Info

Please run the command `./gradlew debugEnv` from the root directory of DJL (if necessary, clone DJL first). It will output information about your system, environment, and installation that can help us debug your issue. Paste the output of the command below:

```
Microsoft Windows [Version 10.0.18362.657]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\MyWorks\DJL-AI\djl>gradlew debugEnv
Found C:\MyWorks\DJL-AI\djl\\gradle\wrapper\gradle-wrapper.jar

> Configure project :mxnet:mxnet-engine
[WARN ] Header file has been changed in open source project: mxnet/c_api.h.
[WARN ] Header file has been changed in open source project: nnvm/c_api.h.

> Task :integration:debugEnv
[INFO ] - ----------System Properties----------
[INFO ] - sun.desktop: windows
[INFO ] - awt.toolkit: sun.awt.windows.WToolkit
[INFO ] - java.specification.version: 12
[INFO ] - sun.cpu.isalist: amd64
[INFO ] - sun.jnu.encoding: Cp1252
[INFO ] - java.class.path: C:\MyWorks\DJL-AI\djl\integration\build\classes\java\main;C:\MyWorks\DJL-AI\djl\integration\build\resources\main;C:\Users\MasudRahman\.gradle\caches\modules-2\files-2.1\commons-cli\commons-cli\1.4\c51c00206bb913cd8612b24abd9fa98ae89719b1\commons-cli-1.4.jar;C:\Users\MasudRahman\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-slf4j-impl\2.12.1\14973e22497adaf0196d481fb99c5dc2a0b58d41\log4j-slf4j-impl-2.12.1.jar;C:\MyWorks\DJL-AI\djl\basicdataset\build\libs\basicdataset-0.3.0-SNAPSHOT.jar;C:\MyWorks\DJL-AI\djl\model-zoo\build\libs\model-zoo-0.3.0-SNAPSHOT.jar;C:\Users\MasudRahman\.gradle\caches\modules-2\files-2.1\org.testng\testng\6.8.1\8aebea980eee079365df20f0cf7fcac900d50250\testng-6.8.1.jar;C:\MyWorks\DJL-AI\djl\mxnet\mxnet-model-zoo\build\libs\mxnet-model-zoo-0.3.0-SNAPSHOT.jar;C:\MyWorks\DJL-AI\djl\mxnet\mxnet-engine\build\libs\mxnet-engine-0.3.0-SNAPSHOT.jar;C:\Users\MasudRahman\.gradle\caches\modules-2\files-2.1\ai.djl.mxnet\mxnet-native-auto\1.6.0-c-SNAPSHOT\88086d340572c8452ce22c76b233e05974add594\mxnet-native-auto-1.6.0-c-SNAPSHOT.jar;C:\MyWorks\DJL-AI\djl\pytorch\pytorch-model-zoo\build\libs\pytorch-model-zoo-0.3.0-SNAPSHOT.jar;C:\MyWorks\DJL-AI\djl\pytorch\pytorch-engine\build\libs\pytorch-engine-0.3.0-SNAPSHOT.jar;C:\MyWorks\DJL-AI\djl\repository\build\libs\repository-0.3.0-SNAPSHOT.jar;C:\MyWorks\DJL-AI\djl\api\build\libs\api-0.3.0-SNAPSHOT.jar;C:\Users\MasudRahman\.gradle\caches\modules-2\files-2.1\org.slf4j\slf4j-api\1.7.26\77100a62c2e6f04b53977b9f541044d7d722693d\slf4j-api-1.7.26.jar;C:\Users\MasudRahman\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-core\2.12.1\4382e93136c06bfb34ddfa0bb8a9fb4ea2f3df59\log4j-core-2.12.1.jar;C:\Users\MasudRahman\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-api\2.12.1\a55e6d987f50a515c9260b0451b4fa217dc539cb\log4j-api-2.12.1.jar;C:\Users\MasudRahman\.gradle\caches\modules-2\files-2.1\org.beanshell\bsh\2.0b4\a05f0a0feefa8d8467ac80e16e7de071489f0d9c\bsh-2.0b4.jar;C:\Users\MasudRahman\.gradle\caches\modules-2\files-2.1\com.beust\jcommander\1.27\58c9cbf0f1fa296f93c712f2cf46de50471920f9\jcommander-1.27.jar;C:\Users\MasudRahman\.gradle\caches\modules-2\files-2.1\org.yaml\snakeyaml\1.6\a1e23e31c424d566ee27382e373d73a28fdabd88\snakeyaml-1.6.jar;C:\Users\MasudRahman\.gradle\caches\modules-2\files-2.1\com.google.code.gson\gson\2.8.5\f645ed69d595b24d4cf8b3fbb64cc505bede8829\gson-2.8.5.jar;C:\Users\MasudRahman\.gradle\caches\modules-2\files-2.1\net.java.dev.jna\jna\5.3.0\4654d1da02e4173ba7b64f7166378847db55448a\jna-5.3.0.jar
[INFO ] - java.vm.vendor: Oracle Corporation
[INFO ] - sun.arch.data.model: 64
[INFO ] - user.variant:
[INFO ] - java.vendor.url: https://java.oracle.com/
[INFO ] - user.timezone: America/Toronto
[INFO ] - java.vm.specification.version: 12
[INFO ] - os.name: Windows 10
[INFO ] - org.apache.logging.log4j.assignedSequences: 159
[INFO ] - user.country: CA
[INFO ] - sun.java.launcher: SUN_STANDARD
[INFO ] - sun.boot.library.path: C:\Program Files\Java\jdk-12.0.2\bin
[INFO ] - sun.java.command: ai.djl.integration.util.DebugEnvironment
[INFO ] - jdk.debug: release
[INFO ] - sun.cpu.endian: little
[INFO ] - user.home: C:\Users\MasudRahman
[INFO ] - user.language: en
[INFO ] - java.specification.vendor: Oracle Corporation
[INFO ] - java.version.date: 2019-07-16
[INFO ] - java.home: C:\Program Files\Java\jdk-12.0.2
[INFO ] - file.separator: \
[INFO ] - java.vm.compressedOopsMode: 32-bit
[INFO ] - line.separator:

[INFO ] - java.vm.specification.vendor: Oracle Corporation
[INFO ] - java.specification.name: Java Platform API Specification
[INFO ] - java.awt.graphicsenv: sun.awt.Win32GraphicsEnvironment
[INFO ] - user.script:
[INFO ] - sun.management.compiler: HotSpot 64-Bit Tiered Compilers
[INFO ] - java.runtime.version: 12.0.2+10
[INFO ] - user.name: MasudRahman
[INFO ] - path.separator: ;
[INFO ] - os.version: 10.0
[INFO ] - java.runtime.name: Java(TM) SE Runtime Environment
[INFO ] - file.encoding: windows-1252
[INFO ] - java.vm.name: Java HotSpot(TM) 64-Bit Server VM
[INFO ] - java.vendor.url.bug: https://bugreport.java.com/bugreport/
[INFO ] - java.io.tmpdir: C:\Users\MASUDR~1\AppData\Local\Temp\
[INFO ] - java.version: 12.0.2
[INFO ] - user.dir: C:\MyWorks\DJL-AI\djl\integration
[INFO ] - os.arch: amd64
[INFO ] - java.vm.specification.name: Java Virtual Machine Specification
[INFO ] - sun.os.patch.level:
[INFO ] - java.library.path: C:\Program Files\Java\jdk-12.0.2\bin;C:\windows\Sun\Java\bin;C:\windows\system32;C:\windows;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk-12.0.2\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.4.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\WiX Toolset v3.11\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\MyWorks\MySofts\apache-maven-3.6.3\bin;C:\MyWorks\DJL-AI\gradle-6.2\bin;C:\Users\MasudRahman\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\MasudRahman\AppData\Local\Programs\Python\Python37\;C:\Users\MasudRahman\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\bin;;C:\Users\MasudRahman\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\;C:\Users\MasudRahman\.dotnet\tools;.
[INFO ] - java.vm.info: mixed mode, sharing
[INFO ] - java.vendor: Oracle Corporation
[INFO ] - java.vm.version: 12.0.2+10
[INFO ] - sun.io.unicode.encoding: UnicodeLittle
[INFO ] - java.class.version: 56.0
[INFO ] -
[INFO ] - ----------Environment Variables----------
[INFO ] - USERDOMAIN_ROAMINGPROFILE: LAPTOP-9GR27E2K
[INFO ] - PROCESSOR_LEVEL: 6
[INFO ] - RegionCode: NA
[INFO ] - SESSIONNAME: Console
[INFO ] - ALLUSERSPROFILE: C:\ProgramData
[INFO ] - PROCESSOR_ARCHITECTURE: AMD64
[INFO ] - PSModulePath: C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules
[INFO ] - SystemDrive: C:
[INFO ] - MOZ_PLUGIN_PATH: C:\Program Files (x86)\Foxit Software\Foxit Reader\plugins\
[INFO ] - DIRNAME: C:\MyWorks\DJL-AI\djl\
[INFO ] - USERNAME: MasudRahman
[INFO ] - CMD_LINE_ARGS: debugEnv
[INFO ] - ProgramFiles(x86): C:\Program Files (x86)
[INFO ] - APP_HOME: C:\MyWorks\DJL-AI\djl\
[INFO ] - CUDA_PATH_V10_1: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
[INFO ] - PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
[INFO ] - DriverData: C:\Windows\System32\Drivers\DriverData
[INFO ] - OneDriveConsumer: C:\Users\MasudRahman\OneDrive
[INFO ] - platformcode: KV
[INFO ] - PyCharm Community Edition: C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\bin;
[INFO ] - ProgramData: C:\ProgramData
[INFO ] - ProgramW6432: C:\Program Files
[INFO ] - HOMEPATH: \Users\MasudRahman
[INFO ] - NVCUDASAMPLES10_1_ROOT: C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.1
[INFO ] - PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
[INFO ] - ProgramFiles: C:\Program Files
[INFO ] - PUBLIC: C:\Users\Public
[INFO ] - windir: C:\windows
[INFO ] - =::: ::\
[INFO ] - _SKIP: 2
[INFO ] - LOCALAPPDATA: C:\Users\MasudRahman\AppData\Local
[INFO ] - USERDOMAIN: LAPTOP-9GR27E2K
[INFO ] - LOGONSERVER: \\LAPTOP-9GR27E2K
[INFO ] - JAVA_HOME: C:\Program Files\Java\jdk-12.0.2
[INFO ] - PROMPT: $P$G
[INFO ] - OneDrive: C:\Users\MasudRahman\OneDrive
[INFO ] - =C:: C:\MyWorks\DJL-AI\djl
[INFO ] - APPDATA: C:\Users\MasudRahman\AppData\Roaming
[INFO ] - DOWNLOAD_URL: "https://raw.githubusercontent.com/gradle/gradle/master/gradle/wrapper/gradle-wrapper.jar"
[INFO ] - JAVA_EXE: C:\Program Files\Java\jdk-12.0.2/bin/java.exe
[INFO ] - NVTOOLSEXT_PATH: C:\Program Files\NVIDIA Corporation\NvToolsExt\
[INFO ] - CommonProgramFiles: C:\Program Files\Common Files
[INFO ] - Path: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk-12.0.2\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.4.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\WiX Toolset v3.11\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\MyWorks\MySofts\apache-maven-3.6.3\bin;C:\MyWorks\DJL-AI\gradle-6.2\bin;C:\Users\MasudRahman\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\MasudRahman\AppData\Local\Programs\Python\Python37\;C:\Users\MasudRahman\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\bin;;C:\Users\MasudRahman\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\;C:\Users\MasudRahman\.dotnet\tools
[INFO ] - OS: Windows_NT
[INFO ] - COMPUTERNAME: LAPTOP-9GR27E2K
[INFO ] - NVCUDASAMPLES_ROOT: C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.1
[INFO ] - CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
[INFO ] - OnlineServices: Online Services
[INFO ] - PROCESSOR_REVISION: 8e0c
[INFO ] - CLASSPATH: C:\MyWorks\DJL-AI\djl\\gradle\wrapper\gradle-wrapper.jar
[INFO ] - CommonProgramW6432: C:\Program Files\Common Files
[INFO ] - ComSpec: C:\windows\system32\cmd.exe
[INFO ] - APP_BASE_NAME: gradlew
[INFO ] - NVCUDASAMPLES9_0_ROOT: C:\ProgramData\NVIDIA Corporation\CUDA Samples\v9.0
[INFO ] - SystemRoot: C:\windows
[INFO ] - TEMP: C:\Users\MASUDR~1\AppData\Local\Temp
[INFO ] - HOMEDRIVE: C:
[INFO ] - USERPROFILE: C:\Users\MasudRahman
[INFO ] - TMP: C:\Users\MASUDR~1\AppData\Local\Temp
[INFO ] - CUDA_PATH_V9_0: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0
[INFO ] - CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
[INFO ] - NUMBER_OF_PROCESSORS: 8
[INFO ] -
[INFO ] - ----------Default Engine----------
Exception in thread "main" java.util.ServiceConfigurationError: ai.djl.engine.EngineProvider: Provider ai.djl.mxnet.engine.MxEngineProvider could not be instantiated
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:583)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:805)
        at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:723)
        at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
        at ai.djl.engine.Engine.initEngine(Engine.java:46)
        at ai.djl.engine.Engine.<clinit>(Engine.java:41)
        at ai.djl.integration.util.DebugEnvironment.main(DebugEnvironment.java:51)
Caused by: java.lang.ExceptionInInitializerError
        at ai.djl.mxnet.engine.MxEngine.<init>(MxEngine.java:40)
        at ai.djl.mxnet.engine.MxEngineProvider.<clinit>(MxEngineProvider.java:21)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:781)
        ... 5 more
Caused by: java.lang.IllegalStateException: Failed to download MXNet native library
        at ai.djl.mxnet.jna.LibUtils.findLibraryInClasspath(LibUtils.java:134)
        at ai.djl.mxnet.jna.LibUtils.getLibName(LibUtils.java:76)
        at ai.djl.mxnet.jna.LibUtils.loadLibrary(LibUtils.java:67)
        at ai.djl.mxnet.jna.JnaUtils.<clinit>(JnaUtils.java:69)
        ... 13 more
Caused by: java.nio.file.FileAlreadyExistsException: C:\Users\MasudRahman\.mxnet\cache\1.6.0-c-SNAPSHOT-20200218mkl-win-x86_64
        at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:351)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:292)
        at java.base/java.nio.file.Files.move(Files.java:1424)
        at ai.djl.mxnet.jna.LibUtils.downloadMxnet(LibUtils.java:316)
        at ai.djl.mxnet.jna.LibUtils.findLibraryInClasspath(LibUtils.java:132)
        ... 16 more

> Task :integration:debugEnv FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integration:debugEnv'.
> Process 'command 'C:\Program Files\Java\jdk-12.0.2\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 10s
29 actionable tasks: 2 executed, 27 up-to-date

C:\MyWorks\DJL-AI\djl> 
```

**Comment by frankfliu** [comment]
@masud-technope Thanks for reporting this issue.

This is caused by an earlier nightly build failure, and snapshot version has not been published properly. We are working on the fix.

For the time being, you can use following command:
```
cd djl
./gradlew :examples:run
```

**Comment by frankfliu** [comment]
snapshot build is updated. It should work now.

Please refresh your dependency to make sure get latest snapshot:
```
./gradlew run --refresh-dependencies
```

**Comment by masud-technope** [comment]
Hi @frankfliu, thanks for the update. I pulled the latest version, but still getting similar errors.
```
Microsoft Windows [Version 10.0.18362.657]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\MyWorks\DJL-AI\djl>cd examples

C:\MyWorks\DJL-AI\djl\examples>gradlew run --refresh-dependencies
Found C:\MyWorks\DJL-AI\djl\examples\\gradle\wrapper\gradle-wrapper.jar

> Task :run FAILED
Exception in thread "main" java.util.ServiceConfigurationError: ai.djl.engine.EngineProvider: Provider ai.djl.mxnet.engine.MxEngineProvider could not be instantiated
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:583)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:805)
        at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:723)
        at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
        at ai.djl.engine.Engine.initEngine(Engine.java:46)
        at ai.djl.engine.Engine.<clinit>(Engine.java:41)
        at ai.djl.repository.zoo.Criteria$Builder.<init>(Criteria.java:181)
        at ai.djl.repository.zoo.Criteria.builder(Criteria.java:162)
        at ai.djl.examples.inference.ObjectDetection.predict(ObjectDetection.java:59)
        at ai.djl.examples.inference.ObjectDetection.main(ObjectDetection.java:50)
Caused by: java.lang.ExceptionInInitializerError
        at ai.djl.mxnet.engine.MxEngine.<init>(MxEngine.java:40)
        at ai.djl.mxnet.engine.MxEngineProvider.<clinit>(MxEngineProvider.java:21)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:781)
        ... 8 more
Caused by: java.lang.IllegalStateException: Failed to download MXNet native library
        at ai.djl.mxnet.jna.LibUtils.findLibraryInClasspath(LibUtils.java:134)
        at ai.djl.mxnet.jna.LibUtils.getLibName(LibUtils.java:76)
        at ai.djl.mxnet.jna.LibUtils.loadLibrary(LibUtils.java:67)
        at ai.djl.mxnet.jna.JnaUtils.<clinit>(JnaUtils.java:69)
        ... 16 more
Caused by: java.nio.file.FileAlreadyExistsException: C:\Users\MasudRahman\.mxnet\cache\1.6.0-c-SNAPSHOT-20200220mkl-win-x86_64
        at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:351)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:292)
        at java.base/java.nio.file.Files.move(Files.java:1424)
        at ai.djl.mxnet.jna.LibUtils.downloadMxnet(LibUtils.java:316)
        at ai.djl.mxnet.jna.LibUtils.findLibraryInClasspath(LibUtils.java:132)
        ... 19 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk-12.0.2\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
3 actionable tasks: 2 executed, 1 up-to-date

C:\MyWorks\DJL-AI\djl\examples> 
```
The main repository compiles fine, but cannot run the examples.
Please advise the next steps.

**Comment by masud-technope** [comment]
Does it have any issue with JDK 12? I am using JDK 12 and Gradle 6.2.

**Comment by frankfliu** [comment]
Can you clean your mxnet cache folder: C:\Users\MasudRahman\.mxnet\cache
```
rd /s /q C:\Users\MasudRahman\.mxnet\cache\
```
This might caused by corrupted cache files.

**Comment by frankfliu** [comment]
@masud-technope 
There is code issue may cause cache corruption. I'm working on a fix. But the fix can only prevent future corruption. You still need manually clean cache.

**Comment by masud-technope** [comment]
> @masud-technope
> There is code issue may cause cache corruption. I'm working on a fix. But the fix can only prevent future corruption. You still need manually clean cache.

Thanks @frankfliu.  I was able to compile and run the BertQaInference!
